### ISSUE TITLE
New endpoints package breaks TypeScript codegen

### ISSUE THREAD

**Issue by cwoolum** [smithy-lang/smithy-typescript#1048]
I'm consuming a smithy package that recently added the new rules engine and the AWS endpoints package. This now causes errors to occur when trying to build the TypeScript client.  I've tested this with 15.X-18.x.

The error I'm seeing is `src/endpoint/ruleset.ts(10,9): error TS2820: Type '"string"' is not assignable to type '"String" | "Boolean"'. Did you mean '"String"'?`

Here are the package versions that were added

```
Maven-software-amazon-smithy_smithy-rules-engine = 1.x;
Maven-software-amazon-smithy_smithy-aws-endpoints = 1.x;
```

These are the versions of packages being used in my generated `package.json`.

```
      "@aws-crypto/sha256-browser": "3.0.0",
      "@aws-crypto/sha256-js": "3.0.0",
      "@aws-sdk/client-sts": "3.425.0",
      "@aws-sdk/credential-provider-node": "3.425.0",
      "@aws-sdk/middleware-host-header": "3.425.0",
      "@aws-sdk/middleware-logger": "3.425.0",
      "@aws-sdk/middleware-recursion-detection": "3.425.0",
      "@aws-sdk/middleware-signing": "3.425.0",
      "@aws-sdk/middleware-user-agent": "3.425.0",
      "@aws-sdk/region-config-resolver": "3.425.0",
      "@aws-sdk/types": "3.425.0",
      "@aws-sdk/util-endpoints": "3.425.0",
      "@aws-sdk/util-user-agent-browser": "3.425.0",
      "@aws-sdk/util-user-agent-node": "3.425.0",
      "@smithy/config-resolver": "^2.0.11",
      "@smithy/fetch-http-handler": "^2.2.1",
      "@smithy/hash-node": "^2.0.10",
      "@smithy/invalid-dependency": "^2.0.10",
      "@smithy/middleware-content-length": "^2.0.12",
      "@smithy/middleware-endpoint": "^2.0.10",
      "@smithy/middleware-retry": "^2.0.13",
      "@smithy/middleware-serde": "^2.0.10",
      "@smithy/middleware-stack": "^2.0.4",
      "@smithy/node-config-provider": "^2.0.13",
      "@smithy/node-http-handler": "^2.1.6",
      "@smithy/protocol-http": "^3.0.6",
      "@smithy/smithy-client": "^2.1.9",
      "@smithy/types": "^2.3.4",
      "@smithy/url-parser": "^2.0.10",
      "@smithy/util-base64": "^2.0.0",
      "@smithy/util-body-length-browser": "^2.0.0",
      "@smithy/util-body-length-node": "^2.1.0",
      "@smithy/util-defaults-mode-browser": "^2.0.13",
      "@smithy/util-defaults-mode-node": "^2.0.15",
      "@smithy/util-retry": "^2.0.3",
      "@smithy/util-utf8": "^2.0.0"
```

**Comment by kuhe** [comment]
Your endpoint ruleset has a parameter with type "string" lowercase, is that right?

Should be fixed in the linked PR, due in the next version of https://www.npmjs.com/package/@smithy/types.
As a workaround, can you use "String" in your ruleset?

**Comment by kuhe** [comment]
The version will be the one after the now-current https://www.npmjs.com/package/@smithy/types/v/2.3.5, TBD. The release GitHub Action is in progress.

**Comment by cwoolum** [comment]
Let me ask the team that owns it. I don't control that package but it seems
like an easy enough fix if it doesn't break their other clients.

**Comment by kuhe** [comment]
The package in question is being migrated from `@aws-sdk/util-endpoints` to `@smithy/util-endpoints`. I'll be making the change in both packages.

**Comment by cwoolum** [comment]
Short term, I was able to get the team to fix the casing. Now that the new packages have been released, TypeScript codegen is broken again with the following mesage

```
src/endpoint/endpointResolver.ts(15,28): error TS2345: Argument of type 'import("{redacted}/.__tmp/node_modules/@smithy/types/dist-types/endpoints/RuleSetObject").RuleSetObject' is not assignable to parameter of type 'import("{redacted}/.__tmp/node_modules/@aws-sdk/util-endpoints/dist-types/types/RuleSetObject").RuleSetObject'.
```
