### ISSUE TITLE
packageJson configuration is not deeply merged

### ISSUE THREAD

**Issue by everett1992** [smithy-lang/smithy-typescript#1125]
I tried to add a npm lifecycle script vai typescript-codegen's `packageJson` in smithy-build.json but instead of the "prepare" script being merging into the scripts block the whole block is replaced. 

#### smithy-build.json
```
"packageJson": {
  "scripts-2": {
    "prepare": "npm pkg set --json version=$(npm pkg get 'dependencies.@aws-sdk/core')"
  }
}
```

#### Before
```
    "scripts": {
        "build": "concurrently 'npm:build:cjs' 'npm:build:es' 'npm:build:types'",
        "build:cjs": "tsc -p tsconfig.cjs.json",
        "build:docs": "typedoc",
        "build:es": "tsc -p tsconfig.es.json",
        "build:types": "tsc -p tsconfig.types.json",
        "build:types:downlevel": "downlevel-dts dist-types dist-types/ts3.4",
        "clean": "rimraf ./dist-* && rimraf *.tsbuildinfo",
        "prepack": "npm run clean && npm run build"
    },
```

#### After
```
    "scripts": {
        "prepare": "npm pkg set --json version=$(npm pkg get 'dependencies.@aws-sdk/core')"
    },
```

**Comment by everett1992** [comment]
In case the X Y problem is more interesting, I want the generated package version to match the @aws-sdk/core version, so its easier to align custom client dependencies with the sdks.

If I could run this after code gen and before publishing the pacakge the version would always match.
```
npm pkg set --json version=$(npm pkg get 'dependencies.@aws-sdk/core')
```

**Comment by kuhe** [comment]
merged the PR allowing merging of the `scripts` package.json field. This will be available in the next Smithy release presumed to be version 0.25.0 since the current is 0.24.0
