### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by mr-mad-e** [smithy-lang/smithy-typescript#1169]
`
../../../node_modules/.pnpm/@smithy+util-endpoints@1.1.1/node_modules/@smithy/util-endpoints/dist-es/utils/callFunction.js -> ../../../node_modules/.pnpm/@smithy+util-endpoints@1.1.1/node_modules/@smithy/util-endpoints/dist-es/utils/evaluateExpression.js -> ../../../node_modules/.pnpm/@smithy+util-endpoints@1.1.1/node_modules/@smithy/util-endpoints/dist-es/utils/callFunction.js
../../../node_modules/.pnpm/@smithy+util-endpoints@1.1.1/node_modules/@smithy/util-endpoints/dist-es/utils/getEndpointProperties.js -> ../../../node_modules/.pnpm/@smithy+util-endpoints@1.1.1/node_modules/@smithy/util-endpoints/dist-es/utils/getEndpointProperty.js -> ../../../node_modules/.pnpm/@smithy+util-endpoints@1.1.1/node_modules/@smithy/util-endpoints/dist-es/utils/getEndpointProperties.js
../../../node_modules/.pnpm/@smithy+util-endpoints@1.1.1/node_modules/@smithy/util-endpoints/dist-es/utils/evaluateRules.js -> ../../../node_modules/.pnpm/@smithy+util-endpoints@1.1.1/node_modules/@smithy/util-endpoints/dist-es/utils/evaluateTreeRule.js -> ../../../node_modules/.pnpm/@smithy+util-endpoints@1.1.1/node_modules/@smithy/util-endpoints/dist-es/utils/evaluateRules.js
../../../node_modules/.pnpm/@smithy+util-stream@2.1.1/node_modules/@smithy/util-stream/dist-es/blob/Uint8ArrayBlobAdapter.js -> ../../../node_modules/.pnpm/@smithy+util-stream@2.1.1/node_modules/@smithy/util-stream/dist-es/blob/transforms.js -> ../../../node_modules/.pnpm/@smithy+util-stream@2.1.1/node_modules/@smithy/util-stream/dist-es/blob/Uint8ArrayBlobAdapter.js
../../../node_modules/.pnpm/@aws-crypto+crc32@3.0.0/node_modules/@aws-crypto/crc32/build/index.js -> ../../../node_modules/.pnpm/@aws-crypto+crc32@3.0.0/node_modules/@aws-crypto/crc32/build/aws_crc32.js -> ../../../node_modules/.pnpm/@aws-crypto+crc32@3.0.0/node_modules/@aws-crypto/crc32/build/index.js
`

**Comment by kuhe** [comment]
We currently use turbporepo for builds which indicates there are no longer any circular dependencies.
