### ISSUE TITLE
TypeError:  Type 'SerdeFunctions & EndpointBearer' is missing the following properties from type 'SerdeContext': requestHandler, disableHostPrefix

### ISSUE THREAD

**Issue by BrianMaldo** [smithy-lang/smithy-typescript#1184]
I get the following output when trying to build the example project:

➜ typescript-client-codegen yarn build
yarn run v1.22.21
warning package.json: No license field
$ concurrently 'yarn:build:cjs' 'yarn:build:es' 'yarn:build:types'
warning package.json: No license field
warning package.json: No license field
warning package.json: No license field
$ tsc -p tsconfig.es.json
$ tsc -p tsconfig.types.json
$ tsc -p tsconfig.cjs.json
[build:cjs] src/commands/GetCityCommand.ts(102,60): error TS2345: Argument of type '(input: GetCityCommandInput, context: SerdeContext) => Promise<HttpRequest>' is not assignable to parameter of type 'RequestSerializer<any, SerdeFunctions & EndpointBearer>'.
[build:cjs]   Types of parameters 'context' and 'context' are incompatible.
[build:cjs]     Type 'SerdeFunctions & EndpointBearer' is missing the following properties from type 'SerdeContext': requestHandler, disableHostPrefix
[build:cjs] src/commands/GetCurrentTimeCommand.ts(91,60): error TS2345: Argument of type '(input: GetCurrentTimeCommandInput, context: SerdeContext) => Promise<HttpRequest>' is not assignable to parameter of type 'RequestSerializer<any, SerdeFunctions & EndpointBearer>'.
[build:cjs]   Types of parameters 'context' and 'context' are incompatible.
[build:cjs]     Type 'SerdeFunctions & EndpointBearer' is not assignable to type 'SerdeContext'.
[build:cjs] src/commands/GetForecastCommand.ts(96,60): error TS2345: Argument of type '(input: GetForecastCommandInput, context: SerdeContext) => Promise<HttpRequest>' is not assignable to parameter of type 'RequestSerializer<any, SerdeFunctions & EndpointBearer>'.
[build:cjs]   Types of parameters 'context' and 'context' are incompatible.
[build:cjs]     Type 'SerdeFunctions & EndpointBearer' is not assignable to type 'SerdeContext'.
[build:cjs] src/commands/ListCitiesCommand.ts(103,60): error TS2345: Argument of type '(input: ListCitiesCommandInput, context: SerdeContext) => Promise<HttpRequest>' is not assignable to parameter of type 'RequestSerializer<any, SerdeFunctions & EndpointBearer>'.
[build:cjs]   Types of parameters 'context' and 'context' are incompatible.
[build:cjs]     Type 'SerdeFunctions & EndpointBearer' is not assignable to type 'SerdeContext'.

**Comment by kuhe** [comment]
This should be fixed by https://github.com/smithy-lang/smithy-typescript/pull/1183, specifically https://www.npmjs.com/package/@smithy/middleware-serde/v/2.2.1
