### ISSUE TITLE
Using AWS protocol traits (e.g. `aws.protocol#restJson1`) in isolation from other traits (e.g. `aws.api#service`)

### ISSUE THREAD

**Issue by Petroniuss** [smithy-lang/smithy-typescript#1242]
Hi,

I want to ask for clarification whether providing `aws.api#service` trait is required alongside `aws.protocol#restJson1`.
The official example for generating typescript clients mentions only `@restJson1` trait.
https://smithy.io/2.0/guides/using-code-generation/update-model.html#id4.

Including `@service` annotation triggers aws-sdk specific codegen to be triggered (including code regarding regions etc), which isn't desireable in case of generating plain http clients (not part of aws sdk). 

It seems to me that it wasn't required to add `@service` annotation in 0.19.

_Originally posted by @Petroniuss in https://github.com/smithy-lang/smithy-typescript/issues/1229#issuecomment-2049982875_

**Comment by syall** [comment]
The `aws.protocol#restJson1` protocol trait, or [any AWS protocol trait](https://smithy.io/2.0/aws/protocols/index.html), is designed to usable in isolation from the other AWS traits (e.g. `aws.api#service`).

> It seems to me that it wasn't required to add `@service` annotation in 0.19.

Are you experiencing codegen errors without the `aws.api#service` trait applied, or is there a case where codegen fails when using only `aws.protocol#restJson1`?  If so, please provide a full stack trace so we can investigate.

**Comment by syall** [comment]
Awesome! Ff that's the case, I'll close this issue.

Please reopen the issue if there is a problem at codegen time when using `aws.protocol#restJson1` in isolation.
