### ISSUE TITLE
Mismatch in Error Code Handling in Generated Waiter Functions

### ISSUE THREAD

**Issue by RanVaknin** [smithy-lang/smithy-typescript#1283]
#### Issue Description:

There is a discrepancy in how Smithy TypeScript generates waiter functions to handle error codes and their corresponding modeled exceptions. The issue arises because the generated TypeScript code uses the name property of the exception to match errors, but the actual error names returned by AWS differ from the error codes defined in the Smithy model.
Root cause is likely that the [`WaiterGenerator.java`](https://github.com/smithy-lang/smithy-typescript/blob/534128e975c2cc9473402a1c2873f46f064b6880/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/WaiterGenerator.java#L159) code refers to error.name, whereas `awsQueryError` needs proper matching.

#### Example

The Smithy model might define an error with the `awsQueryError` code `DBInstanceNotFound`, but the actual exception name returned by AWS is `DBInstanceNotFoundFault`. This leads to incorrect error matching in the generated code, causing waiter functions to either hang indefinitely or fail to transition correctly when the desired resource state is reached.

Smithy model [definition](https://github.com/aws/aws-models/blob/70ee654171767f3fceaef666fd24962fee068f15/rds/smithy/model.json#L9768-L9784):

```json
"com.amazonaws.rds#DBInstanceNotFoundFault": {
  "type": "structure",
  "members": {
    "message": {
      "target": "com.amazonaws.rds#ExceptionMessage"
    }
  },
  "traits": {
    "aws.protocols#awsQueryError": {
      "code": "DBInstanceNotFound",
      "httpResponseCode": 404
    },
    "smithy.api#documentation": "<p>DBInstanceIdentifier doesn't refer to an existing DB instance.</p>",
    "smithy.api#error": "client",
    "smithy.api#httpError": 404
  }
}
```

Generated TypeScript code:

```ts
if (exception.name && exception.name == "DBInstanceNotFound") {
  return { state: "SUCCESS" };
}
```

#### Expected Behavior:
The waiter function should correctly recognize the DBInstanceNotFoundFault exception and transition to the success state.

#### Current Behavior:
The waiter function fails to recognize the DBInstanceNotFoundFault exception, causing it to either hang indefinitely or not transition correctly.

related issue https://github.com/aws/aws-sdk-js-v3/issues/6084

**Comment by kuhe** [comment]
was fixed by @RanVaknin in https://github.com/aws/aws-sdk-js-v3/pull/6501
