### ISSUE TITLE
Force generator to generate models for internal trait

### ISSUE THREAD

**Issue by ayush987goyal** [smithy-lang/smithy-typescript#1294]
Is there a way to force the smithy-ts generator to generate models for all the structures annotated with @internal trait?

**Comment by liushang1997** [comment]
+1

**Comment by kstich** [comment]
This code generator [isn't restricting usage of `@internal` in models by changing the generated code](https://github.com/search?q=repo%3Asmithy-lang%2Fsmithy-typescript%20internaltrai&type=code) for anything significant I can see. Can you share any of the build configuration (smithy-build.json, any other related build config) you're using to run the generator? It sounds like you're running a [projection](https://smithy.io/2.0/guides/smithy-build-json.html#projections) that [transforms](https://smithy.io/2.0/guides/smithy-build-json.html#transforms) the model to remove some internal components.

**Comment by liushang1997** [comment]
I managed to generate internal shapes by removing the following block in smithy-build.json file.
```
"transforms": [{"name": "apply", "args": ["core-aws-sdk-external"]}]
```

**Comment by liushang1997** [comment]
> This code generator [isn't restricting usage of `@internal` in models by changing the generated code](https://github.com/search?q=repo%3Asmithy-lang%2Fsmithy-typescript%20internaltrai&type=code) for anything significant I can see. Can you share any of the build configuration (smithy-build.json, any other related build config) you're using to run the generator? It sounds like you're running a [projection](https://smithy.io/2.0/guides/smithy-build-json.html#projections) that [transforms](https://smithy.io/2.0/guides/smithy-build-json.html#transforms) the model to remove some internal components.

I managed to generate internal shapes by deleting below block in my smithy-build.json file:
```
"transforms": [{"name": "apply", "args": ["core-aws-sdk-external"]}]
```
