### ISSUE TITLE
@smithy/util-stream 3.1.0 causes 'Type 'ReadableStream' is not generic' errors in non-DOM environments

### ISSUE THREAD

**Issue by AaronMoat** [smithy-lang/smithy-typescript#1341]
Hi there, I'm getting this error in `tsc` when going from 3.0.5 to 3.1.0:

```shell
node_modules/@smithy/util-stream/dist-types/stream-type-check.d.ts:4:71 - error TS2315: Type 'ReadableStream' is not generic.

4 export declare const isReadableStream: (stream: unknown) => stream is ReadableStream<any>;
```

I think this is happening in non-DOM environments. Here's an example package.json and tsconfig.json: 

```json
{
  "private": true,
  "resolutions": {
    "@smithy/util-stream": "3.1.0"
  },
  "dependencies": {
    "@aws-sdk/client-sns": "3.606.0"
  },
  "devDependencies": {
    "@types/node": "20.14.11",
    "typescript": "5.5.3"
  }
}
```

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "lib": ["ES2022"],
    "target": "ES2022"
  }
}
```

Setting `"lib": ["ES2022", "DOM"]` does solve it, but not a great outcome.

**Comment by OPthyago** [comment]
I'm facing the same issue.

**Comment by dleavitt** [comment]
Temporary workaround (at least for me):
Add an ambient type declaration like this:
```typescript
// types.d.ts in your source directory or somewhere typescript will see it
interface ReadableStream<T = any> {}
```

**Comment by kuhe** [comment]
I started the release of `@smithy/util-stream@3.1.1`, which should complete in the next 30 minutes. I'm aiming to avoid the insertion of the type parameter by using a type alias.

I'm surprised the TS compiler inserts the type parameter when the source code interface does not include it 🤕.

**Comment by AaronMoat** [comment]
Looks like 3.1.1 fixed it, thanks @kuhe! Yes, the output of the compiler confused me greatly when I was also trying to debug!
