### ISSUE TITLE
httpHandlerInitialization - error - Cannot find name 'RequestInit

### ISSUE THREAD

**Issue by VTLee** [smithy-lang/smithy-typescript#1402]
It appears that [this commit](https://github.com/smithy-lang/smithy-typescript/commit/cf9257e5c37a2eb12d8df257e441b9bf7cc51158#diff-517c07b8245f4dfea4d907892da48b42278316d8453724e5eb755bfc66f368ef) yesterday added a function that references "RequestInit" as a type.

This type is not imported, and results in the following error:

```
../node_modules/@smithy/types/dist-types/http/httpHandlerInitialization.d.ts:114:50 - error TS2304: Cannot find name 'RequestInit'.

114     requestInit?: (httpRequest: IHttpRequest) => RequestInit;
```

I'm not familiar with Smithy / this code base, Just tracing down broken pipelines that appeared today. I can't see a reference to RequestInit in the node modules pulled in for this package.

**Comment by kuhe** [comment]
Created a fix here: https://github.com/smithy-lang/smithy-typescript/pull/1403. This is a global type that is not always present.

**Comment by VTLee** [comment]
> Created a fix here: #1403. This is a global type that is not always present.

Thank you for the prompt response!

**Comment by kuhe** [comment]
We will release a patch version of `@smithy/types` momentarily. As an alternative you can stub the type with

```ts
declare global {
  interface RequestInit {}
}
```

which is what the patch will be doing.

**Comment by kuhe** [comment]
Should appear as https://www.npmjs.com/package/@smithy/types/v/3.4.2 in ~15 minutes.
