### ISSUE TITLE
the latest version 3.2.0 cause deployment on edge failed due to use node module `stream`

### ISSUE THREAD

**Issue by arvinxx** [smithy-lang/smithy-typescript#1435]
we use `@aws-sdk/client-s3` on edge runtime, but the `@smithy/util-stream` use `stream` module break the usage of edge runtime. please revert the [update](https://github.com/smithy-lang/smithy-typescript/commit/f4e0bd9a40c75c7839ec7cb879a467eb1ee34929#diff-8f3d47db43f2656ff1073e159c760813af538af7b72a08f22237477c3696b835) or find a way not to use `stream` module.

```
./node_modules/@smithy/util-stream/dist-es/checksum/ChecksumStream.js:2:1
Module not found: Can't resolve 'stream'
https://nextjs.org/docs/messages/module-not-found
Import trace for requested module:
./node_modules/@smithy/util-stream/dist-es/index.js
./node_modules/@aws-sdk/client-s3/dist-es/runtimeConfig.shared.js
./node_modules/@aws-sdk/client-s3/dist-es/runtimeConfig.browser.js
./node_modules/@aws-sdk/client-s3/dist-es/S3Client.js
./node_modules/@aws-sdk/client-s3/dist-es/index.js
./src/server/modules/S3/index.ts
./src/server/routers/edge/upload.ts
./src/server/routers/edge/index.ts
./src/app/(backend)/trpc/edge/[trpc]/route.ts
```

**Comment by arvinxx** [comment]
@kuhe please check it. I suggest use web native Stream object like [ReadableStream](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream)

**Comment by kuhe** [comment]
I'm releasing a patch that contains bundler file replacement instructions for that file.

**Comment by arvinxx** [comment]
I think it's fixed now. Thanks
