### ISSUE TITLE
`requestTimeout >= 6000` doesn't work

### ISSUE THREAD

**Issue by thomasdax98** [smithy-lang/smithy-typescript#1443]
## Background

I'm using `@aws-sdk/client-s3` to stream videos from an S3 bucket. I experienced issues with socket connections staying open forever if the video stream was interrupted. Thus, I tried setting  `requestTimeout = 15_000` to cleanup connections (as [mentioned in the docs](https://github.com/aws/aws-sdk-js-v3/blob/main/supplemental-docs/CLIENTS.md#nodejs-requesthandler)).  

## Problem

However, the `requestTimeout` didn't work. The request never timed out and the connection still stayed open forever. I experimented with different values and found that `requestTimeout <= 5000` works. But values >= 6000 don't work. 

## Suspected root cause

I looked at the source code and found the following code:

https://github.com/smithy-lang/smithy-typescript/blob/c86a02c231a9efa839238985b531e7b0cf98929e/packages/node-http-handler/src/set-socket-timeout.ts#L18-L26

The timeout is handled differently for values <= 6000. It seems to me as if the code for >= 6000 doesn't work correctly:

https://github.com/smithy-lang/smithy-typescript/blob/c86a02c231a9efa839238985b531e7b0cf98929e/packages/node-http-handler/src/set-socket-timeout.ts#L23-L26

The code above was introduced in https://github.com/smithy-lang/smithy-typescript/pull/1384 and released in [v3.2.0](https://github.com/smithy-lang/smithy-typescript/releases/tag/%40smithy/node-http-handler%403.2.0#:~:text=c86a02c%3A%20defer%20socket%20event%20listeners%20for%20node%3Ahttp). 

I downgraded to version `3.1.4` where timeouts >= 6000 worked again.

**Comment by kuhe** [comment]
Thanks for your report. A fix has been published to https://www.npmjs.com/package/@smithy/node-http-handler/v/3.3.3. 

Your existing client should have a `^` range dependency on this package that allows you to bring in the fix by updating the lockfile, such as with a fresh install. 

The AWS SDK will upgrade to this fixed version at a later date.
