### ISSUE TITLE
Getting `TypeError: Illegal invocation` when calling any AWS SDK method in a browser window in Electron

### ISSUE THREAD

**Issue by massi-ang** [smithy-lang/smithy-typescript#1465]
Hi, after updating the AWS SDK v3 to the latest version I started getting ``TypeError: Illegal invocation` every time the sdk is invoked (eg on `client.send()`).

I narrowed down the problem to the `timings.setTimeout` function. Timing is created as 
```
timings = {
  setTimeout: setTimeout,
  clearTimeout: clearTimeout,
}
```

(see https://github.com/smithy-lang/smithy-typescript/blob/b52b4e8c0a9a43aa5c23f73b65c02df93aeb6cfe/packages/node-http-handler/src/timing.ts#L5-L8)

This causes the two functions to loose the context (`this`) and cause the Illegal invocation error. I verified that reverting back to an SDK version earlier than the date this change was introduced solved the issue.

**Comment by kuhe** [comment]
pending release, expected next Monday. Once the changeset file created in the PR disappears from this folder: https://github.com/smithy-lang/smithy-typescript/tree/main/.changeset, that means it has been released.
