### ISSUE TITLE
aws-sdk/client-route-53  TS1005, '}' expected

### ISSUE THREAD

**Issue by oscarwest** [smithy-lang/smithy-typescript#471]
Hello,

Since aws-sdk-js-v3 uses smithy to generate types, i'm guessing this missing closing curly brace is related to this project, so i'm cross-referencing the issue raised there.

Sorry if this is unrelated.

https://github.com/aws/aws-sdk-js-v3/issues/2921

**Comment by kuhe** [comment]
I believe this has since been fixed.
