### ISSUE TITLE
Improve error handling for unexpected responses.

### ISSUE THREAD

**Issue by everett1992** [smithy-lang/smithy-typescript#555]
Miss-configuration, an overloaded endpoint, proxies or networking issues can all cause unexpected http responses like `500 Service Unavailable` or `302 Please redirect to wifi login portal`.

Smithy typescript generates code for awsJson and awsRest protocols that always tries to parse responses as JSON and throws an unhelpful error  like

```
SyntaxError: Unexpected token C in JSON at position 0
```

I'm not exactly sure what smithy-typescript should do. Logging or throwing an error with the full response body could leak secure information, or simply print too much data. At-least the http status line should be included in the error.

**Comment by everett1992** [comment]
related to aws/aws-sdk-js-v3#4184. The Step Functions service responds to very large requests with 
```
413
 content-type: text; charset=utf-8
 content-length: 43
 date: Mon, 14 Nov 2022 04:04:05 GMT
 connection: close
    
HTTP content length exceeded 1049600 bytes.
 ```
 
 Which isn't a JSON body and doesn't have json content-type. Yet the sdk attempts to parse the response as json and errors
 ```
 Unexpected token H in JSON at position 0
 ```

**Comment by PritamSangani** [comment]
Adding more related issues from https://github.com/aws/aws-sdk-js-v3 repo:

https://github.com/aws/aws-sdk-js-v3/issues/2665
https://github.com/aws/aws-sdk-js-v3/issues/3075
https://github.com/aws/aws-sdk-js-v3/issues/4038
https://github.com/aws/aws-sdk-js-v3/issues/4256

seems to be an issue across multiple service clients, so it would be good if this issue can be prioritised as it makes it very hard (nigh on impossible) to debug error responses from service apis in production.

**Comment by kuhe** [comment]
As of the latest version of the runtime, including for AWS SDKs, deserialization errors append the following message:

```
SyntaxError: Unexpected token H in JSON at position 0
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
    at JSON.parse (<anonymous>)
```

We require users to opt-in to inspecting `error.$response` because we don't want users to inadvertently print sensitive information to logs.

Upon logging the `$response`, you will see:

```
HttpResponse {
  statusCode: 413,
  reason: 'Request Entity Too Large',
  headers: {
    'content-type': 'text; charset=utf-8',
    'content-length': '43',
    date: 'Wed, 21 Aug 2024 14:32:27 GMT',
    connection: 'close'
  },
  body: 'HTTP content length exceeded 1049600 bytes.'
}
```

**Comment by kuhe** [comment]
test code:

```js
import { SFN } from "@aws-sdk/client-sfn";

const sfn = new SFN({ region: "us-west-2" });

console.log(
  await sfn.describeStateMachine({
    stateMachineArn: "a".repeat(1049601),
  }).catch(e => {
    console.error(e);
    console.error(e.$response);
  })
);

```
