### ISSUE TITLE
Potential Bug: new credentials are not assigned to resolved

### ISSUE THREAD

**Issue by limpep** [smithy-lang/smithy-typescript#818]
Hi, the implementation contains a bug I believe. If the value is expired, coalesceProvider() gets called without updating the resolved value. So even if new data is fetched, it won't get returned because resolved remains the same. This could potentially return expired or stale data.

https://github.com/awslabs/smithy-typescript/blob/main/packages/property-provider/src/memoize.ts#L93

I believe it should be 
```
if (isExpired(resolved)) {
  resolved = await coalesceProvider();
  return resolved;
}
```

So, by calling coalesceProvider() without assigning its return value to resolved, we're essentially performing an operation but not using its result. That's why it's important to assign the result of await coalesceProvider() to resolved.

**Comment by kuhe** [comment]
The value of `resolved` is reassigned in the `coalesceProvider` function.
