### ISSUE TITLE
TypeError when calling 'warn' on undefined logger in parse-utils.ts

### ISSUE THREAD

**Issue by rernst76** [smithy-lang/smithy-typescript#855]
There is a TypeError in [packages/smithy-client/src/parse-utils.ts](https://github.com/awslabs/smithy-typescript/blob/main/packages/smithy-client/src/parse-utils.ts) wherein several calls to `logger.warn` `logger` is undefined as it is never imported. 

I stumbled upon this by trying to use the aws-sdk v3 in a Slack Custom Function which uses deno. I am guessing it is some quirk of Slack + Deno that causes this to surface. Regardless, after looking at `parse-utils.ts` it seems like a valid TypeError.

It looks like this could be quickly solved by using the NoOpLogger in [NoOpLogger.ts](https://github.com/awslabs/smithy-typescript/blob/main/packages/smithy-client/src/NoOpLogger.ts).

Let me know if I should open a PR for this.

**Comment by kuhe** [comment]
logger is defined at the bottom of the file in parse-utils
