### ISSUE TITLE
Error: The requested module 'process' does not provide an export named 'geteuid'

### ISSUE THREAD

**Issue by Meags27** [smithy-lang/smithy-typescript#909]
On windows PC, trying to invoke a lambda function from the CLI and that error shows up if you have any Javascript SDK v3 commands in there. E.g dynamodb GetItem etc. 

stack trace:
```js
 E:\Development\sst-site\node_modules\@smithy\shared-ini-file-loader\dist-es\getHomeDir.js:3
   import { geteuid } from "process";
            ^

       at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
       at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

This fixed it but had to change the package itself, would rather a permanent solution

```js
Changed from:
import { geteuid } from "process";
const homeDirCache = {};
const getHomeDirCacheKey = () => {
    if (geteuid) {
        return `${geteuid()}`;
    }
    return "DEFAULT";
};

To this:
import process from "process";
const homeDirCache = {};
const getHomeDirCacheKey = () => {
    if (process.geteuid) {
        return `${process.geteuid()}`;
    }
    return "DEFAULT";
};
```

**Comment by ergo123** [comment]
I have the same issue. It doesn't work on Windows.

**Comment by jayair** [comment]
Is anybody looking at this?

**Comment by JordonPhillips** [comment]
This should be fixed by #916

**Comment by Meags27** [comment]
@JordonPhillips Thanks! Do we have to update this on our end? As I believe this package is a dependency of other packages (I never installed it manually myself)

**Comment by JordonPhillips** [comment]
Yes, you should update your clients to get the newer version
