### ISSUE TITLE
fetch-http-handler: abortSignal, requestTimeout issues

### ISSUE THREAD

**Issue by u873838** [smithy-lang/smithy-typescript#974]
If an abort signal is passed, it is first included in the request options:

https://github.com/awslabs/smithy-typescript/blob/2f70f105a1093c0c5d1caaa84ce292e5917f31ec/packages/fetch-http-handler/src/fetch-http-handler.ts#L99-L101

Then later, the abort signal will be added to the race promises:

https://github.com/awslabs/smithy-typescript/blob/2f70f105a1093c0c5d1caaa84ce292e5917f31ec/packages/fetch-http-handler/src/fetch-http-handler.ts#L144-L154

It seems like the latter block of code can be removed. Relying solely on `fetch`'s internal abort signal signally mechanism seems preferable.

**Comment by kuhe** [comment]
can track release in https://github.com/aws/aws-sdk-js-v3/issues/4872
